### ISSUE TITLE
Feature: to read undivided name list from a text file / ファイルから読み込んで実行する機能追加 

### ISSUE THREAD

**Issue by gatchan0807** [glassmonkey/seimei#22]
English version is bellow Japanese. (From DeepL.com)

--- 

# 概要

移植元の [namedivider-python](https://github.com/rskmoi/namedivider-python) に存在する `file` サブコマンドを移植していただけると嬉しいです。

- https://github.com/rskmoi/namedivider-python#cli
- https://github.com/rskmoi/namedivider-python/blob/master/namedivider/cli.py#L24

## 考えているメリット

- 複数件の名前を分割したい場合に、複数回 `$ seimei --name ${undevidedName}` と呼ぶ必要がなくなるため、コマンド実行のオーバーヘッドがなくなるパフォーマンス改善
- 直接コマンドの引数に分割前の名前が入らなくなるため、OSコマンドインジェクションの実行リスクが低減できる

## 考えうるデメリット

- 複雑なファイル周りの対応が必要になるので、このコマンドのメンテナンスコストが増える点
  - 入力されるファイルの文字コードを考慮する必要がある
  - 一定サイズ以上のファイルを受け付けないようにする必要がある。など。

## 期待しているファイル形式と、ワーストケース

- namedivider-python と同じような形でテキストファイル（1行に1人の分割前フルネーム）を受け取り、標準出力に分割後のフルネームを出力する
- 私のユースケースでは最大でも1GBほどのテキストファイルを読み込み、出力できることを期待しています

---

# About 

It would be great if you could port the file subcommand that exists in the ported [namedivider-python](https://github.com/rskmoi/namedivider-python).

- https://github.com/rskmoi/namedivider-python#cli
- https://github.com/rskmoi/namedivider-python/blob/master/namedivider/cli.py#L24

## Merits

- If you want to split multiple names, you don't have to call `$ seimei --name ${undevidedName}` multiple times, which improves performance by eliminating the overhead of executing the command.
- The risk of OS command injection execution is reduced because the name before the split is no longer included in the direct command argument.

## Demerits

The maintenance cost of this command increases due to the complexity of processing around files.

For example, "it is necessary to consider the character encoding of the input file," "it is necessary to prevent the acceptance of files over a certain size," etc.

**Added missing information**

## Expected file format and worst case

- "namedivider-python" as well as accepts a text file (list with one pre-divider full name per line) and outputs the post-divider full name to standard output.
- I expect to be able to read and output a text file of about 1GB at most for my use case.

**Comment by gatchan0807** [comment]
**不足していた情報の追記**

## 期待しているファイル形式と、ワーストケース

- namedivider-python と同じような形でテキストファイル（1行に1人の分割前フルネーム）を受け取り、標準出力に分割後のフルネームを出力する
- 私のユースケースでは最大でも1GBほどのテキストファイルを読み込み、出力できることを期待しています

---

**Added missing information**

## Expected file format and worst case

- "namedivider-python" as well as accepts a text file (list with one pre-divider full name per line) and outputs the post-divider full name to standard output.
- I expect to be able to read and output a text file of about 1GB at most for my use case.

**Comment by glassmonkey** [comment]
resolve

https://github.com/glassmonkey/seimei/pull/24
https://github.com/glassmonkey/seimei/pull/26
